FEAT: Add ArcusContainer and ArcusClusterContainer.
jam2in/arcus-test-container pull request #1
Opened 2024-05-14 07:40 UTC by brido4125

### 🔗 Related Issue

https://github.com/jam2in/arcus-works/issues/520#issuecomment-2097822968

### ⌨️ What I did

ArcusClusterContainer, ArcusContainer를 설계 및 구현하였습니다.

테스트 코드의 경우 싱글톤으로 ArcusClusterContainer를 
테스트 케이스들이 공유해서 사용하는지를 확인하는 테스트입니다.

추후 가이드 문서에 아래와 같은 방식을 추천할 예정입니다.

2024-05-20 02:39 UTC, uhm0311 requested changes

2024-05-20 02:39 UTC, uhm0311 commented on src/main/java/org/jam2in/ArcusClusterContainer.java
> +    network = Network.newNetwork();
생성자에서 필드에 값을 할당할 때는 `this.`를 붙입시다.

- network
- zkContainer
- cacheNodes
- containers

2024-05-20 02:39 UTC, uhm0311 commented on src/main/java/org/jam2in/ArcusClusterContainer.java
> +    cacheNodes.stream().forEach(s -> containers.add(new ArcusContainer(s, network)));
반복문을 2번 돌 필요가 있나요?

2024-05-20 02:39 UTC, uhm0311 commented on src/main/java/org/jam2in/ArcusClusterContainer.java
> +  private void createZnode(ArrayList<String> cacheNodes) throws IOException, InterruptedException {
cacheNodes 매개변수는 항상 `this.cacheNodes`인데 매개변수를 따로 둘 필요가 있나요?

2024-05-20 02:39 UTC, uhm0311 commented on src/main/java/org/jam2in/ArcusClusterContainer.java
> +  public void start() {
`@Override` 붙일 수 있는 메소드에는 모두 붙입시다.

2024-05-20 02:39 UTC, uhm0311 commented on src/main/java/org/jam2in/ArcusClusterContainer.java
> +public class ArcusClusterContainer extends GenericContainer {
`... extends GenericContainer<ArcusClusterContainer>`

2024-05-20 02:39 UTC, uhm0311 commented on src/main/java/org/jam2in/ArcusContainer.java
> +  public static final DockerImageName DEFAULT_ARCUS_IMAGE_NAME = DockerImageName.parse("jam2in/arcus-memcached");
https://github.com/redis-developer/testcontainers-redis/blob/v2.2.2/subprojects/testcontainers-redis/src/main/java/com/redis/testcontainers/RedisContainer.java

Redis 처럼 도커 이미지 이름과 태그를 선택할 수 있게 합시다.
현재 구현으로는 사설 서버에 저장된 도커 이미지를 가져올 수 없습니다.

2024-05-20 02:39 UTC, uhm0311 commented on src/main/java/org/jam2in/ArcusContainer.java
> +  }
이 생성자는 어디에서 쓰이나요?

2024-05-20 02:39 UTC, uhm0311 commented on src/main/java/org/jam2in/ArcusContainer.java
> +    sb.append("-m 100 -p ").append(port);
지금 보니 메모리 제한도 설정 가능하게 해야 할 것 같습니다.
응용이 어떤 테스트 코드를 수행하느냐에 따라 저장하는 캐시 아이템의 수와 크기가 달라질 수 있기 때문입니다.

2024-05-20 02:39 UTC, uhm0311 commented on src/test/java/org/jam2in/ArcusClusterContainerTest.java
> +    ArcusClientPool arcusClient = ArcusClient.createArcusClientPool("test", new ConnectionFactoryBuilder(), 2);
arcus-java-client를 테스트 코드에서만 사용할 것이라면 arcus-java-client 의존성의 scope를 test로 변경합시다.

2024-05-20 02:39 UTC, uhm0311 commented on src/test/java/org/jam2in/ArcusClusterContainerTest.java
> +import static org.assertj.core.api.Assertions.*;
https://github.com/jam2in/arcus-app-common/commit/3d8e8c096d88f1168fa0d7326298d16fc083d2bd

위 커밋을 참고하여 auto import 세팅을 PR에 포함해주세요.

2024-05-20 02:57 UTC, brido4125 commented on src/main/java/org/jam2in/ArcusContainer.java
> +    sb.append("-m 100 -p ").append(port);
@ing-eoking 
서버에 default로 설정된 메모리 제한 값은 얼마인가요?

2024-05-20 02:58 UTC, brido4125 commented on src/main/java/org/jam2in/ArcusContainer.java
> +  }
`ArcusClusterContainer`에서 내부적으로 캐시 컨테이너 하나 씩 생성할 때 호출됩니다.

2024-05-20 03:40 UTC, ing-eoking commented on src/main/java/org/jam2in/ArcusContainer.java
> +    sb.append("-m 100 -p ").append(port);
64MB입니다

2024-05-21 01:35 UTC, brido4125 commented on src/main/java/org/jam2in/ArcusContainer.java
> +  public static final DockerImageName DEFAULT_ARCUS_IMAGE_NAME = DockerImageName.parse("jam2in/arcus-memcached");
회사 내부적으로도 사설 레지스트리를 사용하는 경우가 있나요?
만약 사용자의 자유도를 위한 구현이라면 추후에 요구사항이 있을 때 추가해줘도 될 것 같습니다.

2024-05-21 01:40 UTC, uhm0311 commented on src/main/java/org/jam2in/ArcusContainer.java
> +  public static final DockerImageName DEFAULT_ARCUS_IMAGE_NAME = DockerImageName.parse("jam2in/arcus-memcached");
일단 네이버에서 사설 서버에 저장해두고 쓰기 때문에 미리 추가하는 것이 맞아 보입니다.
용례를 찾을 수 없는 기능이 아닌, 아주 가까이에서 찾을 수 있는 기능이기 때문입니다.

2024-05-21 01:47 UTC, brido4125 commented on src/main/java/org/jam2in/ArcusContainer.java
> +    sb.append("-m 100 -p ").append(port);
@ing-eoking 

허용 가능한 최대 값은 얼마인가요?

2024-05-21 06:36 UTC, uhm0311 requested changes

2024-05-21 06:36 UTC, uhm0311 commented on src/main/java/org/jam2in/ArcusClusterContainer.java
> +import org.testcontainers.utility.DockerImageName;
auto import 설정에 org.testcontainers 추가합시다.

2024-05-21 06:36 UTC, uhm0311 commented on src/main/java/org/jam2in/ArcusClusterContainer.java
> +import static org.jam2in.ArcusContainer.*;
기본 패키지 경로 `org.jam2in => com.jam2in.arcus.container`

2024-05-21 06:36 UTC, uhm0311 commented on src/main/java/org/jam2in/ArcusContainerProps.java
> +    this.clusterNum = builder.clusterNum;
clusterSize나 countOfNodes와 같은 용어를 씁시다.

2024-05-21 06:36 UTC, uhm0311 commented on src/main/java/org/jam2in/ArcusContainerProps.java
> +  public static class Builder {
Lombok 사용해도 되지 않나요?

2024-05-21 06:36 UTC, uhm0311 commented on src/test/java/org/jam2in/ArcusClusterContainerTestOther.java
> +import static org.assertj.core.api.Assertions.*;
auto import 설정 반영 후 프로젝트 전체에 Optimize imports 해줍시다.

2024-05-21 07:04 UTC, brido4125 commented on src/main/java/org/jam2in/ArcusContainerProps.java
> +  public static class Builder {
`ArcusContainerProps`의 생성자에서만 사용될 것 같아 사용하지 않았습니다.
추후에 더 사용될 만한 곳이 있다면 적용시키도록 하겠습니다.

2024-05-21 07:18 UTC, uhm0311 requested changes

2024-05-21 07:18 UTC, uhm0311 commented on .idea/codeStyles/Project.xml
> +          <package name="org.testcontainers" withSubpackages="true" static="false" />
알파벳 순으로 추가해주세요.
static = true인 경우도 실제론 쓰이지 않더라도 추가해주세요.

2024-05-21 07:18 UTC, uhm0311 commented on pom.xml
> +        </dependency>
이건 scope test로 하지 않아야 하나요?

2024-05-21 07:18 UTC, uhm0311 commented on pom.xml
> +            <version>RELEASE</version>
`5.10.2`와 같이 구체적인 버전을 명시해주세요.

2024-05-21 07:18 UTC, uhm0311 commented on pom.xml
> +            <version>1.19.8</version>
testcontainers 자체에 대한 의존성도 1.19.8로 바꿉시다.

2024-05-21 07:18 UTC, uhm0311 commented on src/main/java/com/jam2in/arcus/testcontainer/ArcusClusterContainer.java
> +import com.github.dockerjava.api.model.ExposedPort;
`com.github.docker-java`도 auto import 설정에 추가합시다.

2024-05-21 07:18 UTC, uhm0311 commented on src/main/java/com/jam2in/arcus/testcontainer/ArcusContainer.java
> +import org.testcontainers.containers.GenericContainer;
패키지를 `com.jam2in.arcus.testcontainer`로 할 거라면 원본 의존성과 동일하게 `com.jam2in.arcus.testcontainers`로 복수형 단어를 씁시다.

2024-05-21 09:12 UTC, uhm0311 approved these changes

2024-05-24 09:08 UTC, oliviarla approved these changes

2024-05-24 11:27 UTC, jhpark816 reviewed
일부 리뷰

2024-05-24 11:27 UTC, jhpark816 commented on src/main/java/com/jam2in/arcus/testcontainers/ArcusContainerProps.java
> +    public Builder clusterNum(int clusterSize) {
용어를 서로 다르게 하는 이유가 있나요?
- clusterNum vs. cluserSize
  - clusterNum은 의미상 맞지 않는 것 같습니다.
  - clusterSize vs. shardCount vs. numOfShards 중에서 선택.
- memSize vs.  memorySize
   - cluster 전체의 memory size인지 or 개별 노드의 memory Size 인지 혼돈이 될 것 같지만,
      eachMemorySize라고 지칭하기 보단 memorySize가 나아 보이긴 합니다.

2024-05-24 11:27 UTC, jhpark816 commented on src/main/java/com/jam2in/arcus/testcontainers/ArcusClusterContainer.java
> +  private static final String CLI_DIR = "./bin/zkCli.sh";
용어 변경 검토
- CLI_DIR => ZKCLI_PATH

2024-05-24 11:27 UTC, jhpark816 commented on src/main/java/com/jam2in/arcus/testcontainers/ArcusClusterContainer.java
> +  private static final String CREATE_CMD = "create";
"create" 문자열을 직접 사용하는 것이 어떤지 ?

2024-05-24 11:27 UTC, jhpark816 commented on src/main/java/com/jam2in/arcus/testcontainers/ArcusClusterContainer.java
> +  private static final String ZNODE_CACHE_SERVER_MAPPING = "/cache_server_mapping";
아래는 어떤지 ?
```java
  private static final String ZPATH_ARCUS = "/arcus";
  private static final String ZPATH_CACHE_LIST = ZPATH_ARCUS + "/cache_list";
  private static final String ZPATH_CLIENT_LIST = ZPATH_ARCUS  + "/client_list";
  private static final String ZPATH_CACHE_SERVER_MAPPING = ZPATH_ARCUS  + "/cache_server_mapping";
```

2024-05-24 11:27 UTC, jhpark816 commented on src/main/java/com/jam2in/arcus/testcontainers/ArcusClusterContainer.java
> +    }
아래와 같이 ZPATH_ 변수를 사용하여 길이를 줄이는 대신
nodeAddr 변수를 사용하는 것이 의미 상 나을 것 같습니다.

 ```java
    for (String nodeAddr : cacheNodes) {
      zkContainer.execInContainer(ZKCLI_PATH, "create", ZPATH_CACHE_SERVER_MAPPING + "/" + nodeAddr);
      zkContainer.execInContainer(ZKCLI_PATH, "create", ZPATH_CACHE_SERVER_MAPPING + "/" + nodeAddr + "/" + serviceCode);
```

2024-05-24 11:27 UTC, jhpark816 commented on src/main/java/com/jam2in/arcus/testcontainers/ArcusClusterContainer.java
> +    containers.stream().forEach(ac -> ac.stop());
아래와 같이 순서가 변경되어야 하지 않는 지 ?

```java
    containers.stream().forEach(ac -> ac.stop());
    zkContainer.stop();
```

2024-05-24 11:27 UTC, jhpark816 commented on src/main/java/com/jam2in/arcus/testcontainers/ArcusClusterContainer.java
> +      String address = "cache" + (i + 1) + ":" + (props.getPort() + i);
아래 형태의 주소를 의도한 것인가요?
- cache1, cache2, cache3가 valid host name인가요?
- port를 모두 동일하게 설정해야 하지 않는 지 ?

```java
cache1:11211
cache2:11212
cache3:11213
```

2024-05-30 00:12 UTC, brido4125 commented on src/main/java/com/jam2in/arcus/testcontainers/ArcusClusterContainer.java
> +  private static final String CREATE_CMD = "create";
여러번 쓰이기에 따로 변수화시키는게 좋을것 같네요

2024-05-30 00:39 UTC, brido4125 commented on src/main/java/com/jam2in/arcus/testcontainers/ArcusClusterContainer.java
> +      String address = "cache" + (i + 1) + ":" + (props.getPort() + i);
> cache1, cache2, cache3가 valid host name인가요?

도커 컨테이너를 생성하기 전 hostname 설정을 해줍니다.

> port를 모두 동일하게 설정해야 하지 않는 지 ?

cluster를 사용하는건데, 도커 컨테이너의 binding 포트를 같게 설정할 이유가 있나요?
현재 arcus docker-compose의 경우도 3개의 컨테이너의 포트를 각각 달리 가집니다.

2024-05-30 01:45 UTC, jhpark816 commented on src/main/java/com/jam2in/arcus/testcontainers/ArcusClusterContainer.java
> +      String address = "cache" + (i + 1) + ":" + (props.getPort() + i);
docket-compose 경우는 1개 장비에 3개 컨테이너 사용한다고 port를 달리한 것입니다.

@uhm0311
위 내용을 검토해 주세요.

2024-05-30 04:46 UTC, uhm0311 commented on src/main/java/com/jam2in/arcus/testcontainers/ArcusClusterContainer.java
> +      String address = "cache" + (i + 1) + ":" + (props.getPort() + i);
테스트 컨테이너도 하나의 장비에 여러 컨테이너를 띄우게 되면 포트를 달리 줘야 합니다.
`port를 모두 동일하게 설정해야` 하는 이유가 무엇인가요?

2024-05-30 04:59 UTC, jhpark816 commented on src/main/java/com/jam2in/arcus/testcontainers/ArcusClusterContainer.java
> +      String address = "cache" + (i + 1) + ":" + (props.getPort() + i);
@brido4125 @uhm0311 
테스트 컨테이너는 하나의 장비에 여러 컨테이너를 구동하는 환경을 가정한 것이군요.

@uhm0311 
이번 리뷰 내용과 수정 내용을 확인한 후에 최종 리뷰를 진행해 주세요.

2024-05-30 08:28 UTC, uhm0311 requested changes

2024-05-30 08:28 UTC, uhm0311 commented on src/main/java/com/jam2in/arcus/testcontainers/ArcusClusterContainer.java
> +  private static final String ZNODE_CACHE_SERVER_MAPPING = ZNODE_ARCUS+ "/cache_server_mapping";
`ZNODE => ZPATH`로 용어 변경합시다.

2024-05-31 00:55 UTC, uhm0311 requested changes

2024-05-31 00:55 UTC, uhm0311 commented on src/main/java/com/jam2in/arcus/testcontainers/ArcusContainerProps.java
> +public class ArcusContainerProps {
`public static Builder builder()` 메소드 추가합시다.

2024-05-31 00:55 UTC, uhm0311 commented on src/main/java/com/jam2in/arcus/testcontainers/ArcusClusterContainer.java
> +        cmd.getHostConfig().withPortBindings(new PortBinding(Ports.Binding.bindPort(DEFAULT_ZK_PORT), new ExposedPort(DEFAULT_ZK_PORT)));
현재 구현으로는 ZK 포트는 항상 2181로 고정인데, 2181 포트를 이미 사용하고 있는 호스트에선 구동이 불가능할 것입니다.
`class ArcusClusterContainerProps extends ArcusContainerProps` 하나 추가해서 ZK 포트도 설정 가능하게 합시다.

2024-05-31 08:28 UTC, brido4125 commented on src/main/java/com/jam2in/arcus/testcontainers/ArcusClusterContainer.java
> +        cmd.getHostConfig().withPortBindings(new PortBinding(Ports.Binding.bindPort(DEFAULT_ZK_PORT), new ExposedPort(DEFAULT_ZK_PORT)));
클래스를 하나 더 생성할 경우 사용자가 더 헷갈릴것 같아
ArcusContainerProps 내에 필드값을 추가하였습니다.

zkPort 필드의 경우, 클러스터를 구성하는 컨테이너를 띄울때만 사용되기에
single 노드로 컨테이너를 띄우는 경우에 영향을 주지 않습니다.

2024-05-31 09:24 UTC, uhm0311 approved these changes

2024-05-31 09:59 UTC, merged