version 0.0.1.SNAPSHOT
jam2in/arcus-test-container pull request #12
Opened 2024-07-01 09:59 UTC by brido4125

### 🔗 Related Issue

-

### ⌨️ What I did

- 0.0.1.SNAPSHOT 릴리즈 커밋입니다.

2024-07-02 00:53 UTC, uhm0311 commented
https://github.com/naver/arcus-spring/commit/50d116cc1a033730a37b925cfd3a105cc44f457d

위 커밋 참고해서 수정해주세요.

2024-07-02 01:59 UTC, uhm0311 requested changes

2024-07-02 01:59 UTC, uhm0311 commented on README.md
> +    <version>0.0.1-SNAPSHOT</version>
본 레포의 pom.xml에 명시된 버전도 수정해야 합니다.

2024-07-02 01:59 UTC, uhm0311 commented on ChangeLog
> +2024-07-01 [version 0.0.1.SNAPSHOT]
pom.xml 버전과 동일한 버전 명을 사용해주세요.

2024-07-02 02:18 UTC, uhm0311 commented
커밋 메세지, PR 제목 수정해주세요.

2024-07-03 07:12 UTC, uhm0311 approved these changes

2024-07-03 07:22 UTC, jhpark816 commented
@uhm0311 
아래 코멘트를 처리하고 나서, version PR을 merge하는 것이 좋겠습니다.
아래 코멘트를 검토해 주시죠.

https://github.com/jam2in/arcus-works/issues/569#issuecomment-2205262531

2024-07-03 07:29 UTC, brido4125 commented
@jhpark816 

arcus-test-container의 테스트 코드에서의 변경인데 
arcus-java-client의 릴리즈까지 기다렸다가 머지해야하는 이유가 따로 있나요?

2024-07-03 07:43 UTC, jhpark816 commented
@brido4125 OK. 바로 merge할게요.

2024-07-03 07:43 UTC, merged