TEST: Add test case and javadoc for ArcusContainer.
jam2in/arcus-test-container pull request #3
Opened 2024-06-03 04:27 UTC by brido4125

### 🔗 Related Issue

아래 이슈에 의해 테스트 코드 isHealthy를 사용하는 케이스는 일부 주석 처리되어있습니다.
https://github.com/jam2in/arcus-test-container/issues/2

### ⌨️ What I did

사용자에게 public으로 공개된 메서드들에 대한 javadoc과
제공하는 클래스에 대한 javadoc을 작성하였습니다.

또한 부족한 test case를 추가하였습니다.

2024-06-05 03:10 UTC, uhm0311 requested changes

2024-06-05 03:10 UTC, uhm0311 commented on src/main/java/com/jam2in/arcus/testcontainers/ArcusContainer.java
>    public static ArcusContainer create(DockerImageName imageName) {
지금 보니 ArcusContainer 클래스에는 DockerImageName과 ArcusContainerProps를 모두 사용자가 설정할 수 있는 메소드는 없습니다.
ArcusClusterContainer 클래스에는 둘 다 설정 가능한 메소드가 있습니다.
ArcusContainer 클래스에만 이런 메소드가 없는 이유가 있나요?
만약 ArcusContainer 클래스에도 추가해야 하는 메소드라면 이번 PR이든 다음 PR이든 추가합시다.

2024-06-05 03:10 UTC, uhm0311 commented on src/main/java/com/jam2in/arcus/testcontainers/ArcusContainerProps.java
> +      }
클러스터 사이즈를 1로 두는 것도 온프레미스 환경이라면 가능합니다.
따라서 0 이하인 경우에만 Exception을 발생시킵시다.

2024-06-05 03:10 UTC, uhm0311 commented on src/main/java/com/jam2in/arcus/testcontainers/ArcusContainerProps.java
> +      }
0번 포트도 사용은 가능합니다.
그리고 최대값인 65535를 넘지 않아야 한다는 조건도 추가합시다.

2024-06-05 03:10 UTC, uhm0311 commented on src/main/java/com/jam2in/arcus/testcontainers/ArcusContainerProps.java
> +      }
여기도 포트 범위를 보강합시다.

2024-06-05 03:10 UTC, uhm0311 commented on src/test/java/com/jam2in/arcus/testcontainers/ArcusClusterContainerTest.java
> +    assertThat(container.isRunning()).isFalse();
start() 이후에 isRunning() == true를 검증할 필요는 없나요?

2024-06-05 04:44 UTC, brido4125 commented on src/test/java/com/jam2in/arcus/testcontainers/ArcusClusterContainerTest.java
> +    assertThat(container.isRunning()).isFalse();
createArcusContainerSingle 테스트 케이스에서
start() 후isRunning을 검증해줍니다.

2024-06-05 08:07 UTC, uhm0311 commented on src/test/java/com/jam2in/arcus/testcontainers/ArcusClusterContainerTest.java
> +    assertThat(container.isRunning()).isFalse();
static으로 사용하는 컨테이너 외에 다양한 create() 메소드로 만든 컨테이너는 실행해볼 필요가 없을까요?

2024-06-10 01:59 UTC, brido4125 commented on src/test/java/com/jam2in/arcus/testcontainers/ArcusClusterContainerTest.java
> +    assertThat(container.isRunning()).isFalse();
create 메소드들의 경우, 하나의 ArcusClusterContainer 생성자의 래퍼 메서드이기에
create 메서드의 인자에 대한 검증과 create를 사용하는 한 경우에 대해서
검증하면 충분하다고 생각합니다.

2024-06-10 02:19 UTC, uhm0311 commented on src/test/java/com/jam2in/arcus/testcontainers/ArcusClusterContainerTest.java
> +    assertThat(container.isRunning()).isFalse();
그럼 `assertThat(container.isRunning()).isFalse();`를 빼도록 합시다.

2024-06-10 03:14 UTC, uhm0311 approved these changes

2024-06-10 03:25 UTC, merged